# Generated by Django 3.0.2 on 2020-01-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.TextField()),
                ('founding_year', models.IntegerField()),
                ('annotation', models.TextField()),
                ('in_action', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capital', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Rekr', 'Rekrut'), ('Gfr', 'Gefreiter'), ('Kpl', 'Korporal'), ('Zgf', 'Zugsfuehrer'), ('Wm', 'Wachtmeister'), ('OWm', 'Oberwachtmeister'), ('StWm', 'Stabswachtmeister'), ('OStWm', 'Oberstabswachtmeister'), ('OStv', 'Offizierstellvertreter'), ('Vzlt', 'Vizeleutnant'), ('Fhr', 'Faehnrich'), ('Lt', 'Leutnant'), ('Olt', 'Oberleutnant'), ('Hptmn', 'Hauptmann'), ('Mjr', 'Major'), ('Obstlt', 'Oberstleutnant'), ('Obst', 'Oberst'), ('Bgdr', 'Brigadier'), ('GenMjr', 'Generalmajor'), ('GenLt', 'Generalleutnant'), ('Gen', 'General')], max_length=6, null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.DateField()),
                ('height', models.IntegerField(help_text='in cm')),
                ('arm_of_service', models.ManyToManyField(blank=True, to='yamod.ArmOfService')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yamod.Country')),
            ],
        ),
        migrations.AddField(
            model_name='armofservice',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yamod.Country'),
        ),
    ]
