# Generated by Django 3.0.2 on 2020-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0002_auto_20200111_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='arm_of_service',
            field=models.ManyToManyField(blank=True, to='yamod.ArmOfService'),
        ),
    ]
